import Lab02.ex1.Book;
import Lab02.ex2.*;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	
	public static void main(String arg[]) {
		
		Lab03.ex2.UIApplication.run(arg);
		
		// Lab 03 2nd Commit
		// Lab 03 3rd Commit
		
//		final String array[] = {"Basic Java", "Advance Java", "Forget about Java"};
//		Book b = new Book(array);
//		System.out.println("The tile of Chapter 1 is " + b.getChapter(1));
//		String anotherArray[] = b.getChapters();
//		
//		System.out.println("There are " + anotherArray.length + " chapters.");
//		System.out.println(java.util.Arrays.toString(anotherArray));
//
//		Computer a = new MobileComputer();
//		for (int i = 0; i < 10; i++) {
//			a.work();
//		}
//		
//		Charger c = new Charger();
//		Phone p = new Phone();
//		MobileComputer m = new MobileComputer();
//		
//		c.charge(p);
//		// This would not compile because m is an instance of Class MobileComputer, and does not inherit Class Chargeable.
//		// So, the Charger instance c would not accept m as a valid argument, so would not compile.
//		// In order to fix this, go back to MobileComputer class and add "implements Chargeable"
//		// Now the class MobileComputer would implement interface Chargeable, so Charger instance can take m as a valid argument
//		c.charge(m); 
	}
	
//    public boolean someLibraryMethod() {
//        return true;
//    }
}
